######################################################################
# Konfiguration des Wolf-ISM8-Servers.
# Je Zeile ein Eintrag, Schluessel und Wert durch ein Leerzeichen getrennt.
# Zeilen mit einem Doppelkreuz werden vom Server uebersprungen -
# deshalb keine Kommentare hinter einem Wert.
######################################################################

enable 0
ism8i_port 12004
input_port 12005
fw_version 1.8
multicast_ip %MS_IP%
multicast_port 35353
dp_log 0
output none
mqtt 1
pull_on_write 0
online_timeout -1
